name = "Nexus"
license = "MIT"
licenselink = "https://github.com/avadlapatla/nexus-hugo-theme/blob/main/LICENSE"
description = "A modern, professional Hugo theme for businesses, agencies, and portfolios with clean design and responsive layout"
homepage = "https://github.com/avadlapatla/nexus-hugo-theme"
tags = ["blog", "business", "corporate", "portfolio", "agency", "responsive", "modern", "clean"]
features = ["responsive", "seo", "accessibility", "fast", "modern"]
min_version = "0.110.0"

[author]
  name = "Nexus Theme Team"
  homepage = "https://github.com/avadlapatla/nexus-hugo-theme"

# Theme supports
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
