# Nexus Theme - Example Config File with Full Customization Options

baseURL = "/"
languageCode = "en-us"
title = "Your Company Name"

# Enable Hugo features
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true

# Site parameters
[params]
  description = "Nexus website for your business, agency or portfolio"
  copyright = "© 2025 Your Company. All rights reserved."
  author = "Your Company"
  
  # Logo (if not provided, site title text will be displayed instead)
  logo = "/images/logo/logo.svg"
  
  # Theme Layout
  [params.layout]
    # Control the order and visibility of sections on homepage
    # Comment out or remove sections you don't want to display
    sections = [
      "hero",      # Hero/banner section
      "services",  # Services section
      "about",     # About section
      "testimonials", # Testimonials section
      "blog",      # Blog posts section
      "contact"    # Contact form section
    ]
  
  # Theme Typography
  [params.typography]
    headingFont = "Poppins, sans-serif"  # Font for headings
    bodyFont = "Inter, sans-serif"       # Font for body text
    baseSize = "16px"                    # Base font size
    scaleRatio = "1.2"                   # Scale between heading sizes
  
  # Theme colors can be customized
  [params.colors]
    primary = "#1a365d"     # Deep navy - Primary brand color
    secondary = "#2d3748"   # Charcoal - Secondary brand color
    accent = "#3182ce"      # Professional blue - Accent color for highlights
    background = "#ffffff"  # Site background
    text = "#1a202c"        # Main text color
    headings = "#1a202c"    # Headings text color
    light = "#f7fafc"       # Light backgrounds
    dark = "#2d3748"        # Dark backgrounds
    borders = "#e2e8f0"     # Border color
    success = "#48bb78"     # Success messages
    error = "#f56565"       # Error messages
    warning = "#ed8936"     # Warning messages
    info = "#4299e1"        # Info messages
    
  # SEO related
  [params.seo]
    [params.seo.meta]
      keywords = ["business", "corporate", "professional", "agency", "consulting"]
      
  # Search functionality (optional)
  [params.search]
    enabled = true
    
  # Hero section
  [params.hero]
    enabled = true
    layout = "standard"  # Options: standard, centered, content-right, full-width
    heading = "Professional Solutions for Modern Businesses"
    subheading = "We deliver cutting-edge solutions that help businesses thrive in the digital age. Our team of experts is dedicated to your success."
    buttonText = "Learn More"
    buttonURL = "#about"
    secondaryButtonText = "Contact Us"
    secondaryButtonURL = "#contact"
    image = "/images/hero/hero-image.jpg"
    imageAlt = "Professional business team"
    pattern = "/images/patterns/hero-pattern.svg"  # Background pattern
    backgroundColor = ""  # Leave empty for theme default, or use hex color code
    textColor = ""        # Leave empty for theme default, or use hex color code
    
  # Services section
  [params.services]
    enabled = true
    layout = "grid"       # Options: grid, list, features, compact
    style = "cards"       # Options: cards, minimal, boxed, bordered
    columns = "3"         # Options: 2, 3, 4
    iconStyle = "default" # Options: default, circle, square, outline
    hoverEffect = "shadow" # Options: shadow, scale, border, none
    title = "Our Services"
    subtitle = "We offer a comprehensive range of services to help your business succeed"
    buttonText = "View All Services"
    buttonURL = "/services"
    backgroundColor = ""  # Optional custom background color
    textColor = ""        # Optional custom text color

# Service items - array of tables using double brackets
[[params.services.items]]
  name = "Strategy Consulting"
  description = "We help businesses develop and implement effective strategies to achieve their goals."
  icon = "/images/icons/strategy.svg"
  link = "/services/strategy-consulting"
  linkText = "Learn More"
      
[[params.services.items]]
  name = "Digital Marketing"
  description = "Our digital marketing services are designed to help businesses reach their target audience and drive growth."
  icon = "/images/icons/marketing.svg"
  link = "/services/digital-marketing"
  linkText = "Learn More"
      
[[params.services.items]]
  name = "Web Development"
  description = "We build modern, responsive websites that help businesses establish a strong online presence."
  icon = "/images/icons/development.svg"
  link = "/services/web-development"
  linkText = "Learn More"
      
  # About section
  [params.about]
    enabled = true
    layout = "standard"         # Options: standard, full-content, stacked
    imagePosition = "left"      # Options: left, right (for standard layout)
    contentWidth = "normal"     # Options: narrow, normal, wide
    showTeam = true             # Whether to show team members
    teamLayout = "grid"         # Options: grid, list
    teamColumns = "4"           # Options: 2, 3, 4 
    title = "About Us"
    subtitle = "We're a team of passionate professionals dedicated to helping businesses succeed"
    image = "/images/about/about.jpg"
    imageAlt = "Our team at work"
    buttonText = "Learn More About Us"
    buttonURL = "/about"
    backgroundColor = ""        # Optional custom background color
    textColor = ""              # Optional custom text color
    content = """
      Founded in 2010, our company has been at the forefront of innovation and excellence in business solutions. We combine expertise, creativity, and technology to deliver outstanding results for our clients.

      Our mission is to empower businesses with the tools and strategies they need to thrive in today's competitive market. We believe in building lasting relationships with our clients based on trust, transparency, and mutual success.
    """
    
  # Key features - array of tables
  [[params.about.features]]
    title = "Client-Focused Approach"
    description = "We prioritize your needs and goals to deliver tailored solutions."
    icon = "/images/icons/client.svg"
      
  [[params.about.features]]
    title = "Innovative Solutions"
    description = "We leverage the latest technologies and methodologies."
    icon = "/images/icons/innovation.svg"
      
  [[params.about.features]]
    title = "Proven Results"
    description = "Our track record speaks for itself with successful case studies."
    icon = "/images/icons/results.svg"
    
  # Team section
  [params.about.team]
    title = "Our Leadership Team"
    subtitle = "Meet the talented individuals behind our success"
      
  [[params.about.team.members]]
    name = "Jane Smith"
    position = "CEO & Founder"
    image = "/images/team/team1.jpg"
    bio = "Jane has over 15 years of experience in the industry and has led the company since its founding."
    [params.about.team.members.social]
      linkedin = "https://linkedin.com/in/janesmith"
      twitter = "janesmith"
      email = "jane@example.com"
          
  [[params.about.team.members]]
    name = "John Doe"
    position = "CTO"
    image = "/images/team/team2.jpg"
    bio = "John leads our technical team with expertise in software development and digital transformation."
    [params.about.team.members.social]
      linkedin = "https://linkedin.com/in/johndoe"
      twitter = "johndoe"
      email = "john@example.com"
          
  [[params.about.team.members]]
    name = "Sarah Johnson"
    position = "Creative Director"
    image = "/images/team/team3.jpg"
    bio = "Sarah brings her creative vision and design expertise to every client project."
    [params.about.team.members.social]
      linkedin = "https://linkedin.com/in/sarahjohnson"
      twitter = "sarahjohnson"
      email = "sarah@example.com"
          
  [[params.about.team.members]]
    name = "Michael Brown"
    position = "Marketing Director"
    image = "/images/team/team4.jpg"
    bio = "Michael has driven successful marketing campaigns for Fortune 500 companies."
    [params.about.team.members.social]
      linkedin = "https://linkedin.com/in/michaelbrown"
      twitter = "michaelbrown"
      email = "michael@example.com"
  
  # Testimonials section
  [params.testimonials]
    enabled = true
    layout = "carousel"          # Options: carousel, grid, simple
    style = "standard"           # Options: standard, modern, minimal
    autoplay = true              # Whether to auto-rotate testimonials
    delay = 5000                 # Delay between slides in ms
    title = "Client Testimonials"
    subtitle = "Hear what our clients have to say about working with us"
    backgroundColor = ""         # Optional custom background color
    textColor = ""               # Optional custom text color
    cardBackgroundColor = ""     # Optional custom card background color
    
  [[params.testimonials.items]]
    quote = "Working with this team has been a game-changer for our business. Their strategic guidance and technical expertise have helped us achieve remarkable growth."
    name = "Robert Wilson"
    position = "CEO"
    company = "Tech Innovations Inc."
    image = "/images/testimonials/testimonial1.jpg"
      
  [[params.testimonials.items]]
    quote = "The team's attention to detail and commitment to excellence exceeded our expectations. They delivered our project on time and on budget, with outstanding results."
    name = "Emily Chen"
    position = "Marketing Director"
    company = "Global Solutions Ltd."
    image = "/images/testimonials/testimonial2.jpg"
      
  [[params.testimonials.items]]
    quote = "Their innovative approach to problem-solving and their deep industry knowledge make them an invaluable partner for any business looking to grow."
    name = "David Rodriguez"
    position = "COO"
    company = "Next Level Enterprises"
    image = "/images/testimonials/testimonial3.jpg"
      
  # Blog section
  [params.blog]
    enabled = true
    layout = "featured"           # Options: featured, grid, list
    style = "cards"               # Options: cards, minimal
    section = "posts"             # Content section to pull posts from
    limit = 3                     # Number of posts to display
    title = "Latest News & Insights"
    subtitle = "Stay up-to-date with our latest articles and industry insights"
    buttonText = "View All Posts"
    buttonURL = "/blog"
    showImages = true             # Whether to show post images
    showAuthors = true            # Whether to show post authors
    showDate = true               # Whether to show post dates
    showCategories = true         # Whether to show post categories
    showExcerpts = true           # Whether to show post excerpts
    excerptLength = 180           # Length of excerpts for main posts
    secondaryExcerptLength = 100  # Length for secondary/smaller posts
    dateFormat = "January 2, 2006" # Date format
    featuredLabel = "Featured"     # Label for featured posts
    readMoreText = "Read Article"  # Text for read more links
    secondaryReadMoreText = "Read" # Text for secondary read more links
    backgroundColor = ""           # Optional custom background color
    textColor = ""                 # Optional custom text color
    
  # Contact section
  [params.contact]
    enabled = true
    layout = "split"              # Options: split, centered, info-above
    style = "standard"            # Options: standard, modern, minimal
    formPosition = "left"         # Options: left, right (for split layout)
    title = "Contact Us"
    subtitle = "Get in touch with our team to discuss your business needs"
    formTitle = "Send us a message"
    formAction = "#"              # Replace with your form handling endpoint
    infoTitle = "Contact Information"
    showSocial = true             # Whether to show social links
    showMap = true                # Whether to show map
    address = "123 Business Street, Suite 100, City, Country"
    addressLabel = "Address"
    phone = "+1 (555) 123-4567"
    phoneLabel = "Phone"
    email = "info@example.com"
    emailLabel = "Email"
    hours = "Monday-Friday: 9AM-5PM"
    hoursLabel = "Business Hours"
    formBackgroundColor = ""      # Optional custom form background color
    infoBackgroundColor = ""      # Optional custom info background color
    backgroundColor = ""          # Optional custom section background color
    textColor = ""                # Optional custom text color
    mapIframe = '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d387193.305935303!2d-74.25986548248684!3d40.69714941932609!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sca!4v1619545303202!5m2!1sen!2sca" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy"></iframe>'
    
  # Social links
  [params.social]
    twitter = "yourcompany"
    facebook = "https://facebook.com/yourcompany"
    instagram = "https://instagram.com/yourcompany"
    linkedin = "https://linkedin.com/company/yourcompany"
    
  # Footer information
  [params.footer]
    description = "We provide professional business solutions to help companies grow and succeed in today's competitive market."
    columns = 4                  # Number of columns in the footer
    showLogo = true              # Whether to show logo in footer
    showSocial = true            # Whether to show social icons in footer
    showNewsletter = true        # Whether to show newsletter form in footer
    copyrightText = "© 2025 Your Company. All rights reserved."

  # Newsletter
  [params.newsletter]
    title = "Subscribe to Our Newsletter"
    description = "Stay updated with our latest news and offers"
    formAction = "#"              # Replace with your newsletter handler

# Main menu
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
    
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 2
    
[[menu.main]]
  identifier = "services"
  name = "Services"
  url = "/services"
  weight = 3
    
[[menu.main]]
  parent = "services"
  name = "Strategy Consulting"
  url = "/services/strategy-consulting"
  weight = 1
      
[[menu.main]]
  parent = "services"
  name = "Digital Marketing"
  url = "/services/digital-marketing"
  weight = 2
      
[[menu.main]]
  parent = "services"
  name = "Web Development"
  url = "/services/web-development"
  weight = 3
  
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog"
  weight = 4
    
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"
  weight = 5

# Footer menus
[[menu.footer]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
    
[[menu.footer]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 2
    
[[menu.footer]]
  identifier = "services"
  name = "Services"
  url = "/services"
  weight = 3
    
[[menu.footer]]
  identifier = "blog"
  name = "Blog"
  url = "/blog"
  weight = 4
    
[[menu.footer]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"
  weight = 5

[[menu.services]]
  identifier = "strategy"
  name = "Strategy Consulting"
  url = "/services/strategy-consulting"
  weight = 1
    
[[menu.services]]
  identifier = "marketing"
  name = "Digital Marketing"
  url = "/services/digital-marketing"
  weight = 2
    
[[menu.services]]
  identifier = "development"
  name = "Web Development"
  url = "/services/web-development"
  weight = 3

[[menu.legal]]
  identifier = "privacy"
  name = "Privacy Policy"
  url = "/privacy-policy"
  weight = 1
    
[[menu.legal]]
  identifier = "terms"
  name = "Terms of Service"
  url = "/terms-of-service"
  weight = 2
